gallery = [
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
    {
        eventTitle: '',
        eventpic1: '',
        eventpic2: '',
        eventpic3: '',
        eventpic4: '',
    },
];

module.exports = gallery;
