newteam = [
    {
        img: 'Manuel.jpg',
        name: 'Manuel',
        desg: 'President',
        insta: 'manuel_u13?igshid=MzNlNGNkZWQ4Mg==',
        linkedin: 'manuel-ullagaddi-3a3883227',
        mail: 'manuelmonu84@gmail.com',
    },
    {
        img: 'Janhavi.jpg',
        name: 'Janhavi',
        desg: 'Vice-President',
        insta: '_._janu07_._?igshid=MzNlNGNkZWQ4Mg==',
        linkedin: 'janhavishinde0707',
        mail: 'sjanhavi0707@gmail.com',
    },
    {
        img: 'Prathamesh.jpg',
        name: 'Prathamesh',
        desg: 'Treasurer',
        insta: 'prathmesh_shete?igshid=NGExMmI2YTkyZg==',
        linkedin: 'prathamesh-shete-05b1ba254',
        mail: 'prathameshshete31@gmail.com',
    },
    {
        img: 'Arya.jpg',
        name: 'Arya',
        desg: 'Social Media Head',
        insta: 'arya__0824/',
        linkedin: 'arya-bangale-a5290b277',
        mail: 'aryabangale0824@gmail.com',
    },
    {
        img: 'Aditya.jpeg',
        name: 'Aditya',
        desg: 'Technical Lead',
        insta: 'aak1112004?igshid=ZGUzMzM3NWJiOQ==',
        linkedin: 'aditya-kumawat-441376231',
        mail: 'adityakumawat2004@gmail.com',
    },
    {
        img: 'Shreya.jpg',
        name: 'Shreya',
        desg: 'Event Organizer',
        insta: 'shreyapandekar?igshid=MzNlNGNkZWQ4Mg==',
        linkedin: 'shreya-pandekar-5a7688231',
        mail: 'pandekarshreya@gmail.com',
    },
    {
        img: 'Ayush.jpeg',
        name: 'Ayush',
        desg: 'Doc. Coordinator',
        insta: 'itz_ayush_ds?igshid=ZGUzMzM3NWJiOQ==',
        linkedin: 'ayush-shastrakar-42bb31229',
        mail: 'ayushshastrakar@gmail.com',
    },
    {
        img: 'Mansi.jpg',
        name: 'Manasi',
        desg: 'PR & Marketing',
        insta: 'mansi_bhosale1420?igshid=MzNlNGNkZWQ4Mg==',
        linkedin: 'mansi-bhosale-784b21231',
        mail: 'mmbhosale21@gmail.com',
    },
    {
        img: 'Jyotika.jpg',
        name: 'Jyotika',
        desg: 'Non-Technical Lead',
        insta: 'jyotika.5?igshid=NGExMmI2YTkyZg==',
        linkedin: 'jyotika-k-95325023b',
        mail: 'sjyotika408@gmail.com',
    },
    {
        img: 'Shivam.jpg',
        name: 'Shivam',
        desg: 'Event Organizer',
        insta: 'shivam_17_atre?igshid=MzNlNGNkZWQ4Mg==',
        linkedin: 'shivam-atre-30650524a',
        mail: 'shivamatre003@gmail.com',
    },
    {
        img: 'Akansha.jpg',
        name: 'Akansha',
        desg: 'Doc. Coordinator',
        insta: 'akanksshhaaa27?igshid=ZDc4ODBmNjlmNQ==',
        linkedin: 'akanksha-tupvihire-523bb7231',
        mail: 'tupvihireakanksha@gmail.com',
    },
    {
        img: 'Simintini.jpg',
        name: 'Simintini',
        desg: 'PR & Marketing',
        insta: 'simintini07?igshid=ZGUzMzM3NWJiOQ==',
        linkedin: 'simintini-pangare-402a3a231',
        mail: 'simipangare27500@gmail.com',
    },
    {
        img: 'Rohit.jpeg',
        name: 'Rohit',
        desg: 'Creative Lead',
        insta: 'rohit_meshram02?igshid=NGExMmI2YTkyZg==',
        linkedin: 'rohit-meshram-630bb7231',
        mail: 'rohitmeshram8793@gmail.com',
    },
    {
        img: 'Akshay.png',
        name: 'Akshay',
        desg: 'Graphics Designer',
        insta: 'akshay.t0703?igshid=MzRlODBiNWFlZA==',
        linkedin: 'akshay-thite-322b3b230',
        mail: 'akshaythite0703@gmail.com',
    },
    {
        img: 'Parth.jpg',
        name: 'Parth',
        desg: 'Content Creator',
        insta: '_goku_instinct_?igshid=MzRlODBiNWFlZA==',
        linkedin: 'parth-dake-611a17278',
        mail: 'parthdake2@gmail.com',
    },
    {
        img: 'Swapnil.jpg',
        name: 'Swapnil',
        desg: 'Project Manager',
        insta: '#',
        linkedin: 'swapnil-suryawanshi-399427277',
        mail: 'swapnil.suryawanshi2002@gmail.com',
    },
    {
        img: 'Om.jpeg',
        name: 'Om',
        desg: 'Dept. Coordinator',
        insta: 'ombadrinathnagre?igshid=MzNlNGNkZWQ4Mg==',
        linkedin: 'om-nagre-7ba735276',
        mail: 'omnagare04@gmail.com',
    },
    {
        img: 'Shruti.jpg',
        name: 'Shruti',
        desg: 'Dept. Coordinator',
        insta: '_shrutii_67?igshid=MzNlNGNkZWQ4Mg==',
        linkedin: 'shruti-naik-969b39231',
        mail: 'shrutin216@gmail.com',
    },
    {
        img: 'Pratika.jpg',
        name: 'Pratika',
        desg: 'Dept. Coordinator',
        insta: '_pratika_gawade_?igshid=MzNlNGNkZWQ4Mg==',
        linkedin: 'pratika-gawade-737033277',
        mail: 'pratikagawade01@gmail.com',
    },
    {
        img: 'Yash.jpg',
        name: 'Yash',
        desg: 'Dept. Coordinator',
        insta: 'yash.j09?igshid=ZDc4ODBmNjlmNQ==',
        linkedin: 'yash-jadhav-ab5b2a272',
        mail: 'jadhav.yash2004@gmail.com',
    },
];

module.exports = newteam;
