newteam = [
    {
        img: '/images/newteam/Manuel.jpg',
        name: 'Manuel',
        desg: 'President',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Janhavi.jpg',
        name: 'Janhavi',
        desg: 'Vice-President',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Prathamesh.jpg',
        name: 'Prathamesh',
        desg: 'Treasurer',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Arya.jpg',
        name: 'Arya',
        desg: 'Social Media Head',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Aditya.jpeg',
        name: 'Aditya',
        desg: 'Technical Lead',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Shreya.jpg',
        name: 'Shreya',
        desg: 'Event Organizer',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Ayush.jpeg',
        name: 'Ayush',
        desg: 'Doc. Coordinator',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Mansi.jpg',
        name: 'Manasi',
        desg: 'PR & Marketing',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Jyotika.jpg',
        name: 'Jyotika',
        desg: 'Non-Technical Lead',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Shivam.jpg',
        name: 'Shivam',
        desg: 'Event Organizer',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Akansha.jpg',
        name: 'Akansha',
        desg: 'Doc. Coordinator',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Simintini.jpg',
        name: 'Simintini',
        desg: 'PR & Marketing',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Rohit.jpeg',
        name: 'Rohit',
        desg: 'Creative Lead',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Akshay.png',
        name: 'Akshay',
        desg: 'Graphics Designer',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Parth.jpg',
        name: 'Parth',
        desg: 'Content Creator',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Swapnil.jpg',
        name: 'Swapnil',
        desg: 'Project Manager',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Om.jpeg',
        name: 'Om',
        desg: 'Dept. Coordinator',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Shruti.jpg',
        name: 'Shruti',
        desg: 'Dept. Coordinator',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Pratika.jpg',
        name: 'Pratika',
        desg: 'Dept. Coordinator',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
    {
        img: '/images/newteam/Yash.jpg',
        name: 'Yash',
        desg: 'Dept. Coordinator',
        insta: '#',
        linkedin: '#',
        github: '#',
    },
];

module.exports = newteam;
