oldteam = [
    {
        img: '/images/Christy.jpg',
        name: 'Christy',
        desg: 'President',
        insta: '',
        linkedin: '',
        github: '',
    },
    {
        img: '/images/oldteam/Stuti.jpg',
        name: 'Stuti',
        desg: 'Vice-President',
        insta: '',
        linkedin: '',
        github: '',
    },
    {
        img: '/images/oldteam/Ankita.jpg',
        name: 'Ankita',
        desg: '',
        insta: '',
        linkedin: '',
        github: '',
    },
    {
        img: '/images/oldteam/Pratyush.jpg',
        name: 'Pratyush',
        desg: '',
        insta: '',
        linkedin: '',
        github: '',
    },
    {
        img: '/images/oldteam/Pritee.jpg',
        name: 'Pritee',
        desg: '',
        insta: '',
        linkedin: '',
        github: '',
    },
    {
        img: '/images/oldteam/Sayali.jpg',
        name: 'Sayali',
        desg: '',
        insta: '',
        linkedin: '',
        github: '',
    },
    {
        img: '/images/oldteam/Tanavi.jpg',
        name: 'Tanavi',
        desg: '',
        insta: '',
        linkedin: '',
        github: '',
    },
    {
        img: '/images/oldteam/Tanisha.jpg',
        name: 'Tanisha',
        desg: '',
        insta: '',
        linkedin: '',
        github: '',
    },
    {
        img: '/images/oldteam/Vaishnavi.jpg',
        name: 'Vaishnavi',
        desg: '',
        insta: '',
        linkedin: '',
        github: '',
    },
    {
        img: '/images/oldteam/.jpg',
        name: '',
        desg: '',
        insta: '',
        linkedin: '',
        github: '',
    },
    {
        img: '/images/oldteam/.jpg',
        name: '',
        desg: '',
        insta: '',
        linkedin: '',
        github: '',
    },
    {
        img: '/images/oldteam/.jpg',
        name: '',
        desg: '',
        insta: '',
        linkedin: '',
        github: '',
    },
    {
        img: '/images/oldteam/.jpg',
        name: '',
        desg: '',
        insta: '',
        linkedin: '',
        github: '',
    },
    {
        img: '/images/oldteam/.jpg',
        name: '',
        desg: '',
        insta: '',
        linkedin: '',
        github: '',
    },
    {
        img: '/images/oldteam/.jpg',
        name: '',
        desg: '',
        insta: '',
        linkedin: '',
        github: '',
    },
    {
        img: '/images/oldteam/.jpg',
        name: '',
        desg: '',
        insta: '',
        linkedin: '',
        github: '',
    },
];

module.exports = oldteam;
