oldteam = [
    {
        img: 'Christy.jpg',
        name: 'Christy',
        desg: 'President',
        insta: 'christybijidaniel/',
        linkedin: '',
        mail: '',
    },
    {
        img: 'Stuti.jpg',
        name: 'Stuti',
        desg: 'Vice-President',
        insta: 'stuti_gujarathi_?igshid=MzNlNGNkZWQ4Mg==',
        linkedin: 'stuti-gujarathi-82a334223',
        mail: 'stuti.gujarathi05@gmail.com',
    },
    {
        img: 'Ankita.jpg',
        name: 'Ankita',
        desg: 'Doc. Coordinator',
        insta: 'ankita.andhare11?igshid=MzNlNGNkZWQ4Mg==',
        linkedin: 'ankita-andhare-844327211/',
        mail: 'ankitaandhare11@gmail.com',
    },
    {
        img: 'Pratyush.jpg',
        name: 'Pratyush',
        desg: 'Social Media Head',
        insta: 'myp_prozpekt?igshid=NGExMmI2YTkyZg==',
        linkedin: 'pratyush-sail-a4572a231',
        mail: 'sailpratyush@gmail.com',
    },
    {
        img: 'Pritee.jpg',
        name: 'Pritee',
        desg: 'Doc. Coordinator',
        insta: 'pritee4021?igshid=NGExMmI2YTkyZg==',
        linkedin: 'pritee4021?igshid=NGExMmI2YTkyZg==',
        mail: 'shindepritee76@gmail.com',
    },
    {
        img: 'Sayali.jpg',
        name: 'Sayali',
        desg: 'PR & Marketing',
        insta: 'sayali__1206?igshid=ZDc4ODBmNjlmNQ==',
        linkedin: 'sayali-navgire-656677211',
        mail: 'sayalinavgire12@gmail.com',
    },
    {
        img: 'Tanavi.jpg',
        name: 'Tanavi',
        desg: 'Event Organizer',
        insta: '#',
        linkedin: 'tanavi-parate-92ba24246',
        mail: 'tanaviparate22@gmail.com',
    },
    {
        img: 'Tanisha.jpg',
        name: 'Tanisha',
        desg: 'Creative Lead',
        insta: 'qkrwndbs/',
        linkedin: 'tanisha-sardey/',
        mail: 'tsardey@gmail.com',
    },
    {
        img: 'Vaishnavi.jpg',
        name: 'Vaishnavi',
        desg: 'Event Organizer',
        insta: '_vaishnaviii_11_?igshid=ZGUzMzM3NWJiOQ==',
        linkedin: 'vaishnavi-jadhav-16982821a/',
        mail: 'vaishnavijadhav1104@gmail.com',
    },
    {
        img: 'Abhishek.jpg',
        name: 'Abhishek ',
        desg: 'Video Editor',
        insta: 'abhi_s_m03/',
        linkedin: 'abhishek-mandave-3bb722213/',
        mail: 'abhishekmandave2018@gmail.com',
    },
    {
        img: 'Simrit.jpg',
        name: 'Simrit',
        desg: 'Non-Technical Lead',
        insta: '#',
        linkedin: '#',
        mail: 'simritgill456@gmail.com',
    },
    {
        img: 'Adarsh.jpg',
        name: 'Adarsh',
        desg: 'Treasurer',
        insta: '_adi.patil_?igshid=MzNlNGNkZWQ4Mg==',
        linkedin: 'adarsh-patil-326287213',
        mail: 'patiladi25@gmail.com',
    },
    {
        img: 'Aryan.jpg',
        name: 'Aryan',
        desg: 'Technical Lead',
        insta: 'aryan.01b?igshid=MzNlNGNkZWQ4Mg==',
        linkedin: 'aryan-arlikar-5bb04621a',
        mail: 'arlikararyan@gmail.com',
    },
    {
        img: 'Tanish.jpg',
        name: 'Tanish',
        desg: 'PR & Marketing',
        insta: 'anixh_02?igshid=OGQ5ZDc2ODk2ZA==',
        linkedin: '#',
        mail: 'tanishshendge151@gmail.com',
    },
    {
        img: '.jpg',
        name: '#',
        desg: '#',
        insta: '#',
        linkedin: '#',
        mail: '#',
    },
    {
        img: '.jpg',
        name: '#',
        desg: '#',
        insta: '#',
        linkedin: '#',
        mail: '#',
    },
];

module.exports = oldteam;
